# Symptom-based remedies and precautions
# Sourced from Mayo Clinic, CDC, WHO, WebMD

SYMPTOM_REMEDIES = {
    "high_fever": [
        "Drink plenty of fluids like water, herbal teas, or warm broth to stay hydrated and support recovery.",
        "Apply a cool, damp cloth to your forehead and neck, or take a lukewarm sponge bath to bring down temperature.",
        "Rest fully in a comfortable room — your body heals fastest during sleep.",
        "Take acetaminophen (paracetamol) as directed on the label to reduce fever and ease discomfort.",
    ],
    "headache": [
        "Drink plenty of water, as dehydration frequently triggers headaches.",
        "Apply a cold or warm compress to your forehead or neck for soothing relief.",
        "Rest in a dark, quiet room while gently massaging your temples, neck, or shoulders.",
        "Sip ginger, peppermint, or chamomile tea to ease tension and inflammation.",
    ],
    "cough": [
        "Drink warm honey-lemon water or herbal tea to soothe your throat and thin mucus.",
        "Use a humidifier or inhale steam from a bowl of hot water to moisten airways.",
        "Gargle with warm salt water (half teaspoon in 8 oz water) to reduce throat irritation.",
        "Prop yourself up with extra pillows at night — lying flat worsens coughing.",
    ],
    "breathlessness": [
        "Sit upright and practice pursed-lip breathing — inhale slowly through your nose, exhale through pursed lips.",
        "Use a fan directed at your face — moving air helps reduce the sensation of breathlessness.",
        "Avoid smoke, strong fumes, and allergens that can worsen breathing difficulty.",
        "Stay calm and focus on slow, controlled breathing — anxiety makes breathlessness worse.",
    ],
    "chest_pain": [
        "Stop all physical activity immediately and sit or lie down in a comfortable position.",
        "If you suspect a heart problem, chew an aspirin (325mg) and call emergency services right away.",
        "Try slow, deep breathing to see if the pain eases — this helps if it's muscular or stress-related.",
        "Do NOT ignore persistent chest pain — always seek medical evaluation to rule out serious causes.",
    ],
    "nausea": [
        "Sip ginger tea or chew on small pieces of fresh ginger — a proven natural remedy for nausea.",
        "Eat small, bland meals like crackers, toast, or plain rice instead of large heavy meals.",
        "Breathe in fresh air or inhale peppermint oil for quick relief from nausea.",
        "Avoid strong smells, greasy foods, and lying down immediately after eating.",
    ],
    "vomiting": [
        "Sip oral rehydration solution (ORS) or clear fluids in small, frequent amounts to prevent dehydration.",
        "Rest your stomach for 1-2 hours after vomiting, then start with ice chips and small sips of water.",
        "Follow the BRAT diet (bananas, rice, applesauce, toast) once you can keep fluids down.",
        "Avoid dairy, caffeine, and fatty foods until vomiting has completely stopped for 24 hours.",
    ],
    "fatigue": [
        "Prioritize quality sleep — aim for 7-9 hours in a dark, cool, quiet room.",
        "Stay hydrated and eat balanced meals with iron-rich foods like spinach, lentils, and lean meats.",
        "Take short 15-20 minute walks outdoors — gentle movement and sunlight boost energy naturally.",
        "Reduce screen time before bed and practice relaxation techniques to improve sleep quality.",
    ],
    "joint_pain": [
        "Apply an ice pack for 15-20 minutes to reduce swelling, or use a warm compress for stiffness.",
        "Do gentle range-of-motion exercises and stretching to keep joints flexible.",
        "Take over-the-counter anti-inflammatory medication (ibuprofen) as directed for pain relief.",
        "Rest the affected joint and avoid high-impact activities until pain subsides.",
    ],
    "skin_rash": [
        "Apply calamine lotion or hydrocortisone cream (1%) to soothe itching and irritation.",
        "Take a lukewarm oatmeal bath — colloidal oatmeal is clinically proven to relieve skin irritation.",
        "Wear loose, soft cotton clothing and avoid scratching to prevent worsening or infection.",
        "Use fragrance-free, hypoallergenic moisturizers to keep the affected skin hydrated.",
    ],
    "itching": [
        "Apply a cold compress or ice wrapped in cloth to the itchy area for immediate relief.",
        "Use over-the-counter antihistamines like cetirizine or loratadine to reduce allergic itching.",
        "Moisturize frequently with fragrance-free cream, especially right after bathing.",
        "Avoid hot showers, harsh soaps, and wool clothing which worsen itching.",
    ],
    "stomach_pain": [
        "Sip warm peppermint or chamomile tea to relax stomach muscles and ease cramping.",
        "Apply a warm heating pad to your abdomen for 15-20 minutes to soothe pain.",
        "Eat small, bland meals and avoid spicy, fatty, or acidic foods until pain resolves.",
        "Try lying on your left side — this position aids digestion and reduces discomfort.",
    ],
    "acidity": [
        "Drink cold milk or a glass of water with half a teaspoon of baking soda for quick relief.",
        "Eat smaller, more frequent meals and avoid lying down for 2-3 hours after eating.",
        "Avoid trigger foods like citrus, tomato, coffee, chocolate, and fried/spicy items.",
        "Chew sugar-free gum after meals — it increases saliva production which neutralizes acid.",
    ],
    "diarrhoea": [
        "Drink plenty of ORS, coconut water, or clear broths to replace lost fluids and electrolytes.",
        "Follow the BRAT diet — bananas, rice, applesauce, and toast are gentle on the stomach.",
        "Avoid dairy, caffeine, alcohol, and high-fiber foods until symptoms resolve.",
        "Wash hands thoroughly with soap to prevent spreading if it's caused by infection.",
    ],
    "constipation": [
        "Increase fiber intake gradually — eat more fruits, vegetables, whole grains, and legumes.",
        "Drink at least 8 glasses of water daily to soften stools and promote regular movement.",
        "Exercise for 20-30 minutes daily — walking or light jogging stimulates bowel activity.",
        "Respond to the urge to go promptly — delaying makes constipation worse.",
    ],
    "back_pain": [
        "Apply ice for the first 48 hours to reduce inflammation, then switch to heat therapy.",
        "Stay gently active — bed rest for more than a day actually slows recovery.",
        "Do gentle stretches like knee-to-chest pulls and cat-cow exercises to ease tension.",
        "Sleep on your side with a pillow between your knees to maintain spinal alignment.",
    ],
    "neck_pain": [
        "Apply a warm compress or heating pad to the neck for 15-20 minutes to relax tense muscles.",
        "Do gentle neck stretches — slowly tilt your head side to side and chin to chest.",
        "Use a supportive cervical pillow that maintains the natural curve of your neck while sleeping.",
        "Take regular breaks from screens every 30 minutes and adjust your monitor to eye level.",
    ],
    "dizziness": [
        "Sit or lie down immediately when dizziness starts to prevent falls and injuries.",
        "Stay well-hydrated — dehydration is one of the most common causes of dizziness.",
        "Move slowly when changing positions — sit on the bed for a minute before standing up.",
        "Avoid sudden head movements, bright lights, and looking at screens during episodes.",
    ],
    "burning_micturition": [
        "Drink 8-10 glasses of water daily to dilute urine and flush out bacteria.",
        "Avoid caffeine, alcohol, and spicy foods which irritate the bladder and worsen burning.",
        "Apply a warm heating pad to your lower abdomen to ease pain and discomfort.",
        "Urinate frequently — do not hold it in — and always wipe front to back.",
    ],
    "loss_of_appetite": [
        "Eat small, frequent meals every 2-3 hours instead of three large ones.",
        "Try nutrient-dense foods like smoothies, soups, yogurt, and nuts when full meals feel overwhelming.",
        "Take a short walk before meals — light activity can naturally stimulate appetite.",
        "Stay hydrated but avoid drinking too much water right before meals as it fills you up.",
    ],
    "sweating": [
        "Wear loose, breathable cotton or moisture-wicking clothing to stay cool.",
        "Stay well-hydrated with water and electrolyte drinks to replace lost fluids.",
        "Keep your environment cool with fans or air conditioning when possible.",
        "Avoid spicy foods, caffeine, and alcohol which can trigger excessive sweating.",
    ],
    "chills": [
        "Wrap up in warm blankets and wear layered clothing to maintain body temperature.",
        "Drink warm fluids like herbal tea, warm water with honey, or clear broth.",
        "Rest and allow your body to fight off infection — chills often signal your immune system is active.",
        "Take acetaminophen if chills are accompanied by fever to help regulate temperature.",
    ],
    "weight_loss": [
        "Eat calorie-dense, nutrient-rich foods like nuts, avocados, whole grains, and healthy oils.",
        "Have 5-6 small meals throughout the day rather than 2-3 large ones.",
        "Add protein-rich foods like eggs, lean meat, beans, and dairy to every meal.",
        "Consult a doctor if you've lost more than 5% of body weight in 6-12 months without trying.",
    ],
    "throat_irritation": [
        "Gargle with warm salt water (half teaspoon salt in 8 oz water) 3-4 times daily.",
        "Drink warm honey-lemon water or herbal tea to coat and soothe the irritated throat.",
        "Suck on ice chips or throat lozenges containing menthol for temporary numbing relief.",
        "Use a humidifier to keep air moist — dry air worsens throat irritation.",
    ],
    "muscle_wasting": [
        "Eat protein-rich foods with every meal — eggs, fish, chicken, lentils, and dairy.",
        "Do gentle resistance exercises as approved by your doctor to rebuild muscle strength.",
        "Ensure adequate calorie intake — your body needs extra energy to rebuild muscle tissue.",
        "Consider protein supplements or shakes if you struggle to eat enough through regular meals.",
    ],
    "yellowish_skin": [
        "Rest adequately and avoid all alcohol until liver function normalizes.",
        "Stay hydrated with water and fresh fruit juices to help flush out excess bilirubin.",
        "Eat light, low-fat meals with plenty of fruits and vegetables to support liver recovery.",
        "Seek medical attention promptly — jaundice can indicate serious liver or blood conditions.",
    ],
    "dark_urine": [
        "Increase your water intake significantly — dark urine is most commonly a sign of dehydration.",
        "Avoid alcohol and caffeine which can further dehydrate your body.",
        "Monitor urine color — it should become lighter (pale straw) with adequate hydration.",
        "See a doctor if dark urine persists despite good hydration — it may signal liver issues.",
    ],
    "anxiety": [
        "Practice deep breathing — inhale for 4 counts, hold for 4, exhale for 6 to activate your calm response.",
        "Limit caffeine and sugar which can amplify anxiety and cause jitteriness.",
        "Exercise regularly — even a 20-minute walk releases endorphins that reduce anxiety naturally.",
        "Try progressive muscle relaxation — tense each muscle group for 5 seconds then release.",
    ],
    "swelling_joints": [
        "Apply cold compresses to swollen joints for 15-20 minutes to reduce inflammation.",
        "Elevate the affected limb above heart level to help drain excess fluid.",
        "Take anti-inflammatory medication (ibuprofen) as directed to reduce swelling and pain.",
        "Rest the swollen joint but do gentle range-of-motion exercises to prevent stiffness.",
    ],
    "continuous_sneezing": [
        "Rinse your nasal passages with saline solution to flush out allergens and irritants.",
        "Take an over-the-counter antihistamine like cetirizine for allergic sneezing.",
        "Keep windows closed during high pollen counts and use a HEPA air purifier indoors.",
        "Avoid known triggers like dust, pet dander, strong perfumes, and cigarette smoke.",
    ],
    "shivering": [
        "Bundle up in warm blankets and drink hot fluids like herbal tea or warm broth.",
        "Take a warm (not hot) bath to gradually raise your body temperature.",
        "Rest and avoid cold drafts — your body is working hard to fight off illness.",
        "Take fever-reducing medication if shivering is caused by high fever.",
    ],
    "watering_from_eyes": [
        "Apply a warm, damp cloth over closed eyes for 5-10 minutes to unblock tear ducts.",
        "Use preservative-free artificial tears to soothe irritated eyes.",
        "Avoid rubbing your eyes — it worsens irritation and can spread infection.",
        "Wear sunglasses outdoors to protect eyes from wind, dust, and allergens.",
    ],
    "muscle_pain": [
        "Apply ice for 15-20 minutes to sore muscles, then switch to warm compresses after 48 hours.",
        "Gently stretch and massage the affected area to promote blood flow and healing.",
        "Take OTC pain relief like ibuprofen or acetaminophen as directed for temporary relief.",
        "Stay hydrated and rest — muscle pain often worsens with dehydration and overexertion.",
    ],
    "abdominal_pain": [
        "Sip warm peppermint or ginger tea to ease cramping and relax stomach muscles.",
        "Place a warm heating pad on your abdomen for 15-20 minutes for soothing relief.",
        "Eat bland, easily digestible foods and avoid heavy, spicy, or fried items.",
        "Lie on your left side with knees drawn up to ease gas pain and aid digestion.",
    ],
}

SYMPTOM_PRECAUTIONS = {
    "high_fever": [
        "Seek immediate medical help if fever exceeds 103°F (39.4°C) or lasts more than 3 days.",
        "Watch for danger signs: stiff neck, confusion, difficulty breathing, severe headache, or rash.",
        "Stay hydrated and eat light meals — fever increases fluid loss and energy needs.",
        "Avoid strenuous activity and rest until fever has been gone for at least 24 hours.",
    ],
    "headache": [
        "Stay hydrated daily and eat regular meals — skipping meals can trigger headaches.",
        "Manage stress through exercise, quality sleep (7-9 hours), and limiting screen time.",
        "Avoid known triggers like excessive caffeine, alcohol, bright lights, or loud environments.",
        "Seek medical help if headaches are severe, sudden, frequent, or come with vision changes or nausea.",
    ],
    "cough": [
        "See a doctor if cough lasts more than 3 weeks, produces blood, or comes with high fever.",
        "Cover your mouth when coughing and wash hands frequently to prevent spreading infection.",
        "Avoid smoking and secondhand smoke which irritate airways and worsen coughing.",
        "Stay hydrated — fluids help thin mucus making it easier to cough up.",
    ],
    "breathlessness": [
        "Call emergency services immediately if you experience sudden severe difficulty breathing.",
        "Seek urgent care if breathlessness is accompanied by chest pain, dizziness, or blue lips.",
        "Avoid exertion in extreme heat, cold, or high humidity which worsen breathing problems.",
        "If you have asthma or COPD, always keep your rescue inhaler within reach.",
    ],
    "chest_pain": [
        "Treat any unexplained chest pain as an emergency — call ambulance or go to ER immediately.",
        "Do not ignore chest pain that lasts more than 5 minutes or occurs with arm/jaw pain.",
        "Avoid heavy physical exertion, emotional stress, and large meals if you have heart conditions.",
        "Keep aspirin accessible if you have known heart disease — know when and how to use it.",
    ],
    "nausea": [
        "Avoid lying flat after eating — sit upright or recline at a slight angle for at least 30 minutes.",
        "Eat and drink slowly — rushing food intake makes nausea worse.",
        "See a doctor if nausea persists for more than 2 days or is accompanied by severe pain or blood.",
        "Avoid preparing or being around food when feeling nauseous — strong odors are triggers.",
    ],
    "vomiting": [
        "Seek medical help if vomiting lasts more than 24 hours, contains blood, or causes signs of dehydration.",
        "Do not take solid food until vomiting has stopped for at least 6 hours.",
        "Watch for dehydration signs: dry mouth, dark urine, dizziness, or reduced urination.",
        "Avoid self-medicating with anti-vomiting drugs without doctor's guidance.",
    ],
    "fatigue": [
        "See a doctor if fatigue persists for more than 2 weeks despite adequate rest and nutrition.",
        "Limit caffeine to mornings only — afternoon caffeine disrupts sleep and worsens fatigue.",
        "Maintain a consistent sleep schedule, even on weekends, to regulate your body clock.",
        "Get checked for underlying causes like anemia, thyroid issues, or diabetes if fatigue is chronic.",
    ],
    "joint_pain": [
        "See a doctor if joint pain is accompanied by swelling, redness, warmth, or fever.",
        "Avoid overloading painful joints — use assistive devices if needed.",
        "Maintain a healthy weight — extra weight puts additional stress on weight-bearing joints.",
        "Do not ignore persistent joint pain lasting more than a week — early treatment prevents damage.",
    ],
    "skin_rash": [
        "See a doctor if rash spreads rapidly, blisters, is painful, or comes with fever.",
        "Avoid scratching — it can lead to secondary bacterial infection and scarring.",
        "Note any new products, foods, or medications that may have triggered the rash.",
        "Keep the area clean and dry, and avoid tight clothing over the rash.",
    ],
    "itching": [
        "See a doctor if itching is severe, widespread, lasts more than 2 weeks, or disrupts sleep.",
        "Keep skin moisturized and avoid hot water which strips natural oils and worsens itching.",
        "Trim fingernails short to minimize skin damage from unconscious scratching.",
        "Avoid known irritants — harsh soaps, wool, synthetic fabrics, and fragranced products.",
    ],
    "stomach_pain": [
        "Seek emergency care if pain is sudden and severe, or if abdomen is rigid and tender to touch.",
        "See a doctor if stomach pain lasts more than a few days or comes with fever, vomiting blood, or black stool.",
        "Avoid NSAIDs (ibuprofen, aspirin) for stomach pain — they can worsen certain stomach conditions.",
        "Do not eat heavy meals — stick to bland, easily digestible foods until pain resolves.",
    ],
    "acidity": [
        "Do not lie down within 3 hours of eating — gravity helps keep stomach acid down.",
        "Avoid smoking, which weakens the valve between stomach and esophagus.",
        "See a doctor if acidity occurs more than twice a week — chronic acid reflux needs treatment.",
        "Maintain a healthy weight — excess belly fat increases pressure on the stomach.",
    ],
    "diarrhoea": [
        "Seek medical help if diarrhea lasts more than 2 days, has blood, or causes severe dehydration.",
        "Replace fluids with ORS — plain water alone doesn't replace lost electrolytes.",
        "Practice strict hand hygiene to prevent spreading infection to others.",
        "Avoid anti-diarrheal medications for the first few hours — the body may be flushing out toxins.",
    ],
    "constipation": [
        "See a doctor if constipation lasts more than 3 weeks or involves blood in stool.",
        "Do not rely on laxatives regularly — they can make your bowel dependent on them.",
        "Avoid processed foods, excessive dairy, and red meat which can worsen constipation.",
        "Never strain forcefully — it can cause hemorrhoids and anal fissures.",
    ],
    "back_pain": [
        "See a doctor if back pain radiates down your legs, causes numbness, or follows an injury.",
        "Maintain good posture — slouching puts extra stress on your lower back.",
        "Avoid lifting heavy objects; if you must, bend your knees and keep the load close to your body.",
        "Do not stay in bed for prolonged periods — gentle movement aids recovery.",
    ],
    "neck_pain": [
        "See a doctor if neck pain follows a fall or injury, or comes with numbness or weakness in arms.",
        "Avoid sleeping on your stomach — it strains the neck all night.",
        "Do not crack or forcefully twist your neck — this can damage joints and ligaments.",
        "Maintain ergonomic posture at work — keep screen at eye level and shoulders relaxed.",
    ],
    "dizziness": [
        "Seek emergency care if dizziness comes with sudden headache, chest pain, difficulty breathing, or slurred speech.",
        "Avoid driving, operating machinery, or climbing stairs during dizzy episodes.",
        "Get up slowly from bed or chairs — sudden position changes can trigger dizziness.",
        "See a doctor if dizziness is recurrent or lasts more than a few days.",
    ],
    "burning_micturition": [
        "See a doctor promptly — burning urination usually indicates a urinary tract infection needing antibiotics.",
        "Complete the full course of prescribed antibiotics even if symptoms improve quickly.",
        "Avoid holding urine for long periods — frequent urination helps flush bacteria.",
        "Wear cotton underwear and avoid tight pants to reduce moisture and bacterial growth.",
    ],
    "loss_of_appetite": [
        "See a doctor if appetite loss persists for more than 2 weeks or causes noticeable weight loss.",
        "Don't force large meals — eat nutrient-dense snacks throughout the day.",
        "Rule out underlying causes like depression, thyroid problems, or infections with your doctor.",
        "Avoid filling up on water or low-calorie drinks before meals.",
    ],
    "sweating": [
        "See a doctor if you experience unexplained night sweats or sweating with weight loss.",
        "Stay hydrated to replace fluids lost through sweating.",
        "Wear breathable fabrics and change out of wet clothes promptly to prevent skin issues.",
        "Track patterns — note if sweating occurs with fever, anxiety, or specific medications.",
    ],
    "chills": [
        "See a doctor if chills are persistent, recurring, or accompanied by high fever.",
        "Monitor temperature regularly — chills often precede fever spikes.",
        "Stay warm but don't overheat — use blankets you can easily remove.",
        "Seek emergency care if chills come with confusion, stiff neck, or difficulty breathing.",
    ],
    "anxiety": [
        "Seek professional help if anxiety interferes with daily life, work, or relationships.",
        "Avoid self-medicating with alcohol or drugs — they worsen anxiety long-term.",
        "Limit caffeine and sugar intake which can amplify anxiety symptoms.",
        "Practice regular self-care: exercise, social connection, and consistent sleep schedule.",
    ],
    "muscle_pain": [
        "See a doctor if muscle pain is severe, doesn't improve with rest, or appears without clear cause.",
        "Avoid overexertion — gradually increase exercise intensity to prevent muscle injury.",
        "Stay hydrated during exercise — dehydration contributes to muscle cramps and soreness.",
        "Warm up before physical activity and cool down afterwards to prevent muscle strain.",
    ],
    "abdominal_pain": [
        "Seek emergency care for sudden severe abdominal pain, especially with fever, vomiting, or rigid abdomen.",
        "Avoid eating large or heavy meals when experiencing abdominal discomfort.",
        "Do not take aspirin or ibuprofen for stomach pain — they can irritate the stomach lining.",
        "Keep a food diary to identify potential trigger foods if abdominal pain is recurring.",
    ],
}
